# Generated by Django 4.1.5 on 2023-01-29 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0003_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('87adcf84-d920-4f3a-9aeb-49b7ec0bc8e1'), editable=False, unique=True),
        ),
    ]
