# Generated by Django 4.1.5 on 2023-01-29 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0004_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('80c1eaf2-873e-4c53-8747-78e9809df2bd'), editable=False, unique=True),
        ),
    ]
