# Generated by Django 4.1.5 on 2023-01-29 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0005_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0c0c3316-2d82-45e7-b53c-755d9eccf2fb'), editable=False, unique=True),
        ),
    ]
