# Generated by Django 4.1.5 on 2023-01-29 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0006_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0bc58781-82d4-449f-a888-2745d7b17024'), editable=False, unique=True),
        ),
    ]
