# Generated by Django 4.1.7 on 2023-04-04 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0008_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/pfp/default.png', upload_to='media/pfp/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
