# Generated by Django 4.1.7 on 2023-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0010_alter_imagepost_onlineservice'),
        ('aiart_auth', '0010_customuser_liked_image_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorited_image_posts',
            field=models.ManyToManyField(related_name='favorited_image_posts', to='aiart_content.imagepost'),
        ),
    ]
