# Generated by Django 4.1.7 on 2023-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0011_customuser_favorited_image_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=24),
        ),
    ]
