# Generated by Django 4.1.7 on 2023-05-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0012_customuser_bio_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
