# Generated by Django 4.1.7 on 2023-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0013_remove_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='', max_length=250),
        ),
    ]
