# Generated by Django 4.1.7 on 2023-05-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_auth', '0015_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
    ]
