# Generated by Django 4.1.7 on 2023-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.AddField(
            model_name='report',
            name='other_option',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_option',
            field=models.CharField(choices=[('report_broken_url', "I can't view the image for this post."), ('report_not_aiart', 'This post is not AI Art.'), ('report_harassment', 'This post is targetted harassment.'), ('report_selfharm', 'This post is promoting suicide or self-harm.'), ('report_spam', 'This post is spam.'), ('report_untagged_sexual_content', 'This post is not tagged for sexual content (18+).'), ('report_sexual_content_minors', 'This post contains sexual content involving minors.'), ('report_other', 'Other (please use the box below)')], default='report_broken_url', max_length=300),
            preserve_default=False,
        ),
    ]
