# Generated by Django 4.1.5 on 2023-01-29 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0003_alter_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cfee9410-5d8c-4219-993e-2bda0294796f'), editable=False, unique=True),
        ),
    ]
