# Generated by Django 4.1.7 on 2023-04-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0005_alter_post_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aiart_content.post')),
                ('image_url', models.URLField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('model_hash', models.CharField(max_length=64)),
                ('hypernetwork', models.CharField(blank=True, max_length=256)),
                ('hypernetwork_hash', models.CharField(blank=True, max_length=64)),
                ('positive_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('generation_details', models.CharField(blank=True, max_length=300)),
                ('isOnlineService', models.BooleanField(default=False)),
                ('onlineService', models.CharField(blank=True, choices=[('DALLE', 'DALL-E 2'), ('NAI', 'NOVEL AI'), ('MJ', 'Midjourney')], max_length=256)),
            ],
            bases=('aiart_content.post',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
