# Generated by Django 4.1.7 on 2023-04-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0007_alter_imagepost_onlineservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='hypernetwork_hash',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='model_hash',
        ),
    ]
