# Generated by Django 4.1.7 on 2023-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0008_remove_imagepost_hypernetwork_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='model',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
