# Generated by Django 4.1.7 on 2023-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0009_alter_imagepost_model_alter_imagepost_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='onlineService',
            field=models.CharField(blank=True, choices=[('DALL-E', 'DALL-E 2'), ('Novel AI', 'Novel AI'), ('Midjourney', 'Midjourney')], max_length=256),
        ),
    ]
