# Generated by Django 4.1.7 on 2023-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiart_content', '0011_comment_imagepostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
